services:
  - type: web
    name: turk-teknik-server
    env: node
    repo: https://github.com/emirkn/serverproject
    branch: main
    buildCommand: npm install
    startCommand: npm start
    plan: free
